/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class natif_natifUpd */

#ifndef _Included_natif_natifUpd
#define _Included_natif_natifUpd
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     natif_natifUpd
 * Method:    mapUp
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_natif_natifUpd_mapUp
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
